# Unified libp2p Website Configuration
# Consolidates: website-new, blog, docs, connectivity-site

base_url = "/"
title = "libp2p - A modular network stack"
description = "Run your network applications free from runtime and address services, independently of their location."
author = "The libp2p Foundation"

# Compile Sass files in the sass directory
compile_sass = true

# Build search index for JavaScript search
build_search_index = true

# Generate RSS feed
generate_feeds = true
feed_filenames = ["rss.xml"]

# Default language
default_language = "en"

# Generate a sitemap
generate_sitemap = true

# Syntax highlighting
[markdown]
insert_anchor_links = "heading"

[markdown.highlighting]
enabled = true
theme = "monokai"

# Taxonomies for blog
[[taxonomies]]
name = "tags"
feed = true

[[taxonomies]]
name = "authors"

# Link checking
[link_checker]
skip_prefixes = [
    "https://github.com/libp2p/",
]
skip_anchor_prefixes = []

# Search configuration
[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

# Extra configuration variables
[extra]
# Site metadata
name = "libp2p"
domain = "libp2p.io"
logo = "/img/logo_small.png"

# Repository links
github = "https://github.com/libp2p/libp2p"
site_repo = "https://github.com/libp2p/unified-website"
specs_repo = "https://github.com/libp2p/specs"
specs_url = "https://github.com/libp2p/specs"

# Implementation repositories
implementations = "https://github.com/libp2p/libp2p?tab=readme-ov-file#implementations"
go_libp2p = "https://github.com/libp2p/go-libp2p"
rust_libp2p = "https://github.com/libp2p/rust-libp2p"
js_libp2p = "https://github.com/libp2p/js-libp2p"
py_libp2p = "https://github.com/libp2p/py-libp2p"
nim_libp2p = "https://github.com/vacp2p/nim-libp2p"
zig_libp2p = "https://github.com/zen-eth/zig-libp2p"
cpp_libp2p = "https://github.com/libp2p/cpp-libp2p"
swift_libp2p = "https://github.com/swift-libp2p/swift-libp2p"
jvm_libp2p = "https://github.com/libp2p/jvm-libp2p"
dotnet_libp2p = "https://github.com/NethermindEth/dotnet-libp2p"
c_libp2p = "https://github.com/Pier-Two/c-libp2p"
litep2p = "https://github.com/paritytech/litep2p"

# Discussion forums
discuss = "https://discuss.libp2p.io"
specs_discussions = "https://github.com/libp2p/specs/discussions"
github_discussions = "https://github.com/libp2p/libp2p?tab=readme-ov-file#discussion"

# Chat rooms - Slack
slack_community = "https://filecoinproject.slack.com/archives/C06HV0D00E5"
slack_implementers = "https://filecoinproject.slack.com/archives/C03K82MU486"

# Chat rooms - Discord
discord_community = "https://discord.gg/MRRgEFMAVN"
discord_implementers = "https://discord.gg/Ae4TbahHaT"

# Chat rooms - Telegram
telegram_community = "https://t.me/+gQhmYY_RIBc5NzYx"
telegram_implementers = "https://t.me/+gQhmYY_RIBc5NzYx"

# Chat rooms - Matrix
matrix_community = "https://matrix.to/#/#libp2p-community:matrix.org"
matrix_implementers = "https://matrix.to/#/#libp2p-implementers:ipfs.io"

# Social media
twitter = "https://twitter.com/libp2p"
bluesky = "https://bsky.app/profile/libp2p.bsky.social"

# Events calendar
luma_calendar = "https://lu.ma/libp2p"
luma_embed = "https://lu.ma/embed/calendar/cal-7CPAnJtz4A4aj2X/events?compact=true&lt=light"

# Contact
security_email = "security@libp2p.io"

# Analytics (Umami)
umami_website_id = "b6b8bcd5-2e78-4301-af82-335e10e2baed"

# Release Atom feeds for automated fetching
[extra.release_feeds]
go-libp2p = "https://github.com/libp2p/go-libp2p/releases.atom"
rust-libp2p = "https://github.com/libp2p/rust-libp2p/releases.atom"
js-libp2p = "https://github.com/libp2p/js-libp2p/releases.atom"
nim-libp2p = "https://github.com/vacp2p/nim-libp2p/releases.atom"
py-libp2p = "https://github.com/libp2p/py-libp2p/releases.atom"

# Navigation items (used by topbar template)
[[extra.nav]]
name = "Home"
url = "/"

[[extra.nav]]
name = "Blog"
url = "/blog/"

[[extra.nav]]
name = "Docs"
url = "/guides/"

[[extra.nav]]
name = "Projects"
url = "/projects/"

[[extra.nav]]
name = "Status"
url = "/status/"

[[extra.nav]]
name = "Get Involved"
url = "/get-involved/"

[[extra.nav]]
name = "Reports"
url = "/reports/"

[[extra.nav]]
name = "Specs"
url = "https://github.com/libp2p/specs"
external = true

# Logo wall - Add logos here (images go in static/img/logos/)
[[extra.logos]]
name = "powered-by-libp2p-logo.svg"
alt = "libp2p"
url = "https://libp2p.io"

[[extra.logos]]
name = "filecoin-logo.svg"
alt = "Filecoin"
url = "https://filecoin.io"

[[extra.logos]]
name = "ethereum-logo.svg"
alt = "Ethereum"
url = "https://ethereum.org"

[[extra.logos]]
name = "ipfs-logo.svg"
alt = "IPFS"
url = "https://ipfs.tech"

[[extra.logos]]
name = "celestia-logo.svg"
alt = "Celestia"
url = "https://celestia.org"

[[extra.logos]]
name = "optimism-logo.svg"
alt = "Optimism"
url = "https://optimism.io"

[[extra.logos]]
name = "polygon-logo.svg"
alt = "Polygon"
url = "https://polygon.technology"

[[extra.logos]]
name = "chainlink-logo.svg"
alt = "Chainlink"
url = "https://chain.link"

[[extra.logos]]
name = "uniswap-logo.svg"
alt = "Uniswap"
url = "https://uniswap.org"

[[extra.logos]]
name = "polkadot-logo.svg"
alt = "Polkadot"
url = "https://polkadot.com"

[[extra.logos]]
name = "chainsafe-logo.svg"
alt = "Chainsafe"
url = "https://chainsafe.io"

[[extra.logos]]
name = "arda-logo.svg"
alt = "Arda"
url = "https://arda.co"

[[extra.logos]]
name = "pier-two-logo.svg"
alt = "Pier Two"
url = "https://piertwo.com"

[[extra.logos]]
name = "nethermind-logo.svg"
alt = "Nethermind"
url = "https://nethermind.io"

[[extra.logos]]
name = "peergos-logo.svg"
alt = "Peergos"
url = "https://peergos.org"

[[extra.logos]]
name = "sigma-prime-logo.svg"
alt = "Sigma Prime"
url = "https://sigmaprime.io"

[[extra.logos]]
name = "multiversx-logo.svg"
alt = "MultiversX"
url = "https://multiversx.com"

[[extra.logos]]
name = "aleph-zero-logo.svg"
alt = "Aleph Zero"
url = "https://alephzero.org"

[[extra.logos]]
name = "world-logo.svg"
alt = "World"
url = "https://world.org"

[[extra.logos]]
name = "quiet-logo.svg"
alt = "Quiet"
url = "https://tryquiet.org"

[[extra.logos]]
name = "moonbeam-logo.svg"
alt = "Moonbeam"
url = "https://moonbeam.network"

[[extra.logos]]
name = "oasis-logo.svg"
alt = "Oasis"
url = "https://oasis.net"

[[extra.logos]]
name = "celo-logo.svg"
alt = "Celo"
url = "https://celo.org"

[[extra.logos]]
name = "mina-logo.svg"
alt = "Mina"
url = "https://minaprotocol.com"

[[extra.logos]]
name = "astar-logo.svg"
alt = "Astar"
url = "https://astar.network"

[[extra.logos]]
name = "maidsafe-logo.svg"
alt = "Maidsafe"
url = "https://maidsafe.net"

[[extra.logos]]
name = "hopr-logo.svg"
alt = "Hopr"
url = "https://hoprnet.org"

[[extra.logos]]
name = "berty-logo.svg"
alt = "Berty"
url = "https://berty.tech/messenger"

[[extra.logos]]
name = "mantle-logo.svg"
alt = "Mantle"
url = "https://mantle.xyz"

[[extra.logos]]
name = "algorand-logo.svg"
alt = "Algorand"
url = "https://algorandtechnologies.com"

# Footer links
[[extra.footer_links]]
name = "GitHub"
url = "https://github.com/libp2p"

[[extra.footer_links]]
name = "Specs"
url = "https://github.com/libp2p/specs"

[[extra.footer_links]]
name = "Discuss"
url = "https://discuss.libp2p.io"

[[extra.footer_links]]
name = "Twitter"
url = "https://twitter.com/libp2p"

[[extra.footer_links]]
name = "Bluesky"
url = "https://bsky.app/profile/libp2p.bsky.social"
